services:
  neo4j:
    image: neo4j:latest
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/config:/config
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    networks:
        - db

  data-pipeline:
    volumes:
      - ./data:/data
    build:
      context: ./data-pipeline
    environment:
      - NEO4J_URI
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
    # Make sure the application only starts when the DB is indeed ready
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
        - db


# ----- GPU Profile ------
  sentiment-score-gpu:
    profiles: ["gpu"]
    build:
      context: ./sentiment-score
    environment:
      - NEO4J_URI
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
    depends_on:
      data-pipeline:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
        - db

  demo-app-gpu:
    profiles: ["gpu"]
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - NEO4J_URI
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
    depends_on:
      sentiment-score-gpu:
        condition: service_completed_successfully


# ----- CPU Profile ------
  sentiment-score-cpu:
    profiles: ["cpu"]
    build:
      context: ./sentiment-score
    environment:
      - NEO4J_URI
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
    depends_on:
      data-pipeline:
        condition: service_completed_successfully
    networks:
        - db

  demo-app-cpu:
    profiles: ["cpu"]
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - NEO4J_URI
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
    depends_on:
      sentiment-score-cpu:
        condition: service_completed_successfully

networks:
  db:
